dataset: 
  data_dir: "Fire_Data"

train_data:
  batch_size: 128
  num_workers: 64
  shuffle: True

valid_data:
  batch_size: 64
  num_workers: 1
  shuffle: False

test_data:
  batch_size: 64
  num_workers: 1
  shuffle: False

model:
  in_channel: 114
  hidden_channels: []
  out_channel: 1

optimizer:
  lr: 1e-4

trainer:
  gpus: 1
  # gpus: 4
  # accelerator: "ddp"
  max_epochs: 10000
  check_val_every_n_epoch: 1

logger: 
  save_dir: "training"
  name: "lightning_logs"

callbacks:
  model_checkpoint:
    monitor: "valid_loss"
    mode: "min"
    save_top_k: 3
    save_last: True
    filename: "{epoch}-{valid_loss:.2f}"
    dirpath: "training/checkpoints"



